@API_HostAddress = https://localhost:7215

GET {{API_HostAddress}}/api/groups
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5MmY0NzAxLTcwMDQtNDMyYy05NWYwLTk2MjM2Y2ExZGQxOCIsIm5iZiI6MTcxMjU4ODM5NiwiZXhwIjoxNzE1MTgwMzk2LCJpYXQiOjE3MTI1ODgzOTYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyMTUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjE1In0.RaYHTtx79aI8QkOKYU7VPLEtwARKlivI5yaQ6gXpYOM

# POST {{API_HostAddress}}/api/Auth/login
# Content-Type: application/json
# Accept: application/json

# {
#   "email": "string1",
#   "password": "string"
# }
