@API_HostAddress = https://localhost:7215

GET {{API_HostAddress}}/api/Groups
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkNzQ2YzQ1My1iODQwLTQ3MGQtYWJhZS0xYWZhM2I2MTZkMmEiLCJ1bmlxdWVfbmFtZSI6InN0cmluZyBzdHJpbmciLCJuYmYiOjE3MTE4MDQxOTEsImV4cCI6MTcxNDM5MjU5MSwiaWF0IjoxNzExODA0MTkxLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjE1IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIxNSJ9.ERPS25MtxG1twsEPQu6TM9GZQab_DWvmibJ__2cz4Cc


# POST {{API_HostAddress}}/api/Auth/login
# Content-Type: application/json
# Accept: application/json

# {
#   "email": "string1",
#   "password": "string"
# }
